-- Add offer_copy column to demo_sessions table
-- This column will store personalized offer copy generated by AI based on user's pain point

ALTER TABLE demo_sessions
ADD COLUMN IF NOT EXISTS offer_copy JSONB DEFAULT NULL;

-- Add comment to explain the column purpose
COMMENT ON COLUMN demo_sessions.offer_copy IS 'Personalized offer copy generated by AI based on user pain point. Structure: { head_father, copy_father, head1, copy1, head2, copy2 }';

-- Create index for faster queries on session_id when fetching offer_copy
CREATE INDEX IF NOT EXISTS idx_demo_sessions_offer_copy_session_id 
ON demo_sessions(session_id) 
WHERE offer_copy IS NOT NULL;
