// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ituvfufiknlieynmdngg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml0dXZmdWZpa25saWV5bm1kbmdnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ5NDkxNDgsImV4cCI6MjA3MDUyNTE0OH0.RmNq61gQL3310w7XMtLUe24_iqrypLUBwV6z06lMzsM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});