// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yuorlidtcnhcpuxpqwec.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl1b3JsaWR0Y25oY3B1eHBxd2VjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU0MTUxNTUsImV4cCI6MjA3MDk5MTE1NX0.By-0MFSfslKFmZK9AJGhOLGOrRdqEdFlNF5jsX_cGF8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Browser fingerprinting utility (same as useSupabaseDemo.tsx)
const generateBrowserFingerprint = (): string => {
  const canvas = document.createElement('canvas');
  const ctx = canvas.getContext('2d');
  ctx?.fillText('Demo fingerprint', 10, 10);
  
  const fingerprint = {
    userAgent: navigator.userAgent,
    language: navigator.language,
    platform: navigator.platform,
    screenResolution: `${screen.width}x${screen.height}`,
    timezone: Intl.DateTimeFormat().resolvedOptions().timeZone,
    canvas: canvas.toDataURL(),
    timestamp: Date.now()
  };
  
  return btoa(JSON.stringify(fingerprint)).slice(0, 32);
};

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
  global: {
    headers: {
      'x-session-fingerprint': generateBrowserFingerprint(),
    },
  },
});